import { PageWrapper } from "@/components/PageWrapper";
import { Flex, Heading } from "@aws-amplify/ui-react";
import Head from "next/head";
import { CommonPostCardCollection } from "@/components/CommonPostCardCollection";
import { Amplify, AuthModeStrategyType } from "aws-amplify";
import awsconfig from "../aws-exports";

Amplify.configure({
  ...awsconfig,
  DataStore: {
    authModeStrategyType: AuthModeStrategyType.DEFAULT,
  },
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Simple Amplify Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PageWrapper>
        <Flex width="100%" direction="column" alignItems="center">
          <Heading level={1}>Welcome to Amplify Blog</Heading>
          <CommonPostCardCollection />
        </Flex>
      </PageWrapper>
    </>
  );
}
