import React from "react";
import Head from "next/head";
import { Flex, View } from '@aws-amplify/ui-react';
import { Amplify, AuthModeStrategyType } from "aws-amplify";
import NewPostLayout from "@/components/NewPostLayout";
import {PageWrapper} from "@/components/PageWrapper";
import awsconfig from "@/aws-exports";

Amplify.configure({
  ...awsconfig,
  DataStore: {
    authModeStrategyType: AuthModeStrategyType.MULTI_AUTH,
  },
  ssr: false,
});

export default function NewPost() {
  return (
    <>
      <Head>
        <title>Simple Amplify Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PageWrapper>
        <Flex width="100%" direction="column" alignItems="center" >
            <View width="100%" maxWidth="800px">
              <NewPostLayout />
            </View>
        </Flex>
      </PageWrapper>
    </>
  );
}
